apiVersion: v1
kind: Service
metadata:
  name: sm-user
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: sm-user
  ports:
  - name: user
    port: 4003
    targetPort: 4003
    protocol: TCP
