apiVersion: v1
kind: Service
metadata:
  name: sm-elastic
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: sm-elastic
  ports:
  - name: rest
    port: 9200
    targetPort: 9200
    protocol: TCP
  - name: inter-node
    port: 9300
    targetPort: 9300
    protocol: TCP