apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-notification
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sm-notification
    spec:
      containers:
      - name: sm-notification
        image: libenhailu/sm-notification:stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: notification
          containerPort: 4001
        env:
          - name: ENABLE_APM
            value: "1"
          - name: NODE_ENV
            value: "production"
          - name: CLIENT_URL
            value: "http://localhost:3000"
          - name: RABBITMQ_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sm-rabbitmq-endpoint
          - name: SENDER_EMAIL
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sender-email
          - name: SENDER_EMAIL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sender-email-password
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: elastic-search-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: elastic-apm-secret-token
