apiVersion: v1
kind: Service
metadata:
  name: sm-reaction
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: sm-reaction
  ports:
  - name: reaction
    port: 4007
    targetPort: 4007
    protocol: TCP
