apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-gateway
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: sm-gateway
    spec:
      containers:
      - name: sm-gateway
        image: libenhailu/sm-gateway:stable
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "0.5"
          requests:
            cpu: 100m
            memory: 150Mi
        ports:
        - name: gateway
          containerPort: 4000
        env:
          - name: ENABLE_APM
            value: "1"
          - name: GATEWAY_JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: gateway-jwt-token
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: jwt-token
          - name: NODE_ENV
            value: "production"
          - name: SECRET_KEY_ONE
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: secret-key-one
          - name: SECRET_KEY_TWO
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: secret-key-two
          - name: CLIENT_URL
            value: "http://localhost:3000"
          - name: AUTH_BASE_URL
            value: "http://sm-auth.production.svc.cluster.local:4002"
          - name: USERS_BASE_URL
            value: "http://sm-user.production.svc.cluster.local:4003"
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: redis-host
          - name: ELASTIC_SEARCH_URL
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sm-elasticsearch-url
          - name: ELASTIC_APM_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sm-elastic-apm-server-url
          - name: ELASTIC_APM_SECRET_TOKEN
            valueFrom:
              secretKeyRef:
                name: sm-backend-secret
                key: sm-elastic-apm-secret-token
