apiVersion: v1
kind: Service
metadata:
  name: sm-auth
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: sm-auth
  ports:
  - name: auth
    port: 4002
    targetPort: 4002
    protocol: TCP
