apiVersion: v1
kind: Service
metadata:
  name: sm-post
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: sm-post
  ports:
  - name: post
    port: 4006
    targetPort: 4006
    protocol: TCP
